name: Automation Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "weather_dataset.csv"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      
      # Setup Python 3.12.10
      - name: Set up Python 3.12.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.10"

      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirenments.txt

      # Run Automation Script
      - name: Run Automation
        run: |
          cd preprocessing
          python automate_Andra.py

      # Commit and Push Output
      - name: Commit and Push Cleaned Data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add preprocessing/weather_dataset_preprocessing.csv
          git commit -m "Auto-generated: Update cleaned dataset via GitHub Actions" || echo "No changes to commit"
          git push origin main
